In [1]:
pip install numpy

In [2]:
import numpy as np

In [ ]:
#Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:
#  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.
#  b. Find the indices of elements greater than 10 in the array.


In [3]:
import numpy as np

# Create a 1D NumPy array with integers from 1 to 20
array_1d = np.arange(1, 21)
print("1D NumPy Array:", array_1d)

1D NumPy Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# a. Calculate the sum, mean, median, and standard deviation
array_sum = np.sum(array_1d)
array_mean = np.mean(array_1d)
array_median = np.median(array_1d)
array_std_dev = np.std(array_1d)

print("\n--- OUTPUT OF cALCULATION  ARRAY_ID Array ---")
print(f"Sum: {array_sum}")
print(f"Mean: {array_mean}")
print(f"Median: {array_median}")
print(f"Standard Deviation: {array_std_dev}")


--- OUTPUT OF cALCULATION  Array ---
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [6]:
# b. Find the indices of elements greater than 10
indices_greater_than_10 = np.where(array_1d > 10)

print("\nIndices of elements greater than 10:", indices_greater_than_10[0])
print("Elements greater than 10:", array_1d[indices_greater_than_10])


Indices of elements greater than 10: [10 11 12 13 14 15 16 17 18 19]
Elements greater than 10: [11 12 13 14 15 16 17 18 19 20]


In [7]:
#2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.
# a. Print the array.
# b. Find the transpose of the array.
# c. Calculate the row-wise and column-wise sums of the array.
array_2d = np.arange(1, 17).reshape(4, 4)
print("Original 2D NumPy Array:")
print(array_2d)

Original 2D NumPy Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
# b. Find the transpose of the array.
array_transpose = np.transpose(array_2d)
print("\nTranspose of the array:")
print(array_transpose)


Transpose of the array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [12]:
# c. Calculate the row-wise and column-wise sums of the array.
row_sums = np.sum(array_2d, axis=1)
column_sums = np.sum(array_2d, axis=0)
print("\nRow-wise sums:", row_sums)
print("Column-wise sums:", column_sums)


Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


In [24]:
#3. Create two 3 X 3 arrays filled with random integers between 1 and 20.
# a. Perform element-wise addition, subtraction, and multiplication.
 # b. Compute the dot product of the two arrays.
array_3d = np.random.randint(1, 21, size=(3, 3))
print("First 3D NumPy Array:")
print(array_3d)

First 3D NumPy Array:
[[ 1 19 14]
 [ 6 20 20]
 [ 2 12  6]]


In [28]:
# a. Perform element-wise addition, subtraction, and multiplication.
array_3d_2 = np.random.randint(1, 21, size=(3, 3))
print("Second 3D NumPy Array:")
print(array_3d_2)


Second 3D NumPy Array:
[[ 8 17  9]
 [ 3 18 17]
 [ 8  7 16]]


In [32]:
# addition
addition_result = array_3d + array_3d_2
print("\nElement-wise Addition:")
print(addition_result)
#subtraction
subtraction_result = array_3d - array_3d_2
print("\nElement-wise Subtraction:")
print(subtraction_result)
#multiplication
multiplication_result = array_3d * array_3d_2
print("\nElement-wise Multiplication:")
print(multiplication_result)


Element-wise Addition:
[[ 9 36 23]
 [ 9 38 37]
 [10 19 22]]

Element-wise Subtraction:
[[ -7   2   5]
 [  3   2   3]
 [ -6   5 -10]]

Element-wise Multiplication:
[[  8 323 126]
 [ 18 360 340]
 [ 16  84  96]]


In [34]:
dot_product_result = np.dot(array_3d, array_3d_2)
print("\nDot Product of the two arrays:")
print(dot_product_result)


Dot Product of the two arrays:
[[177 457 556]
 [268 602 714]
 [100 292 318]]


In [40]:
#4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.
array_2d = np.arange(1, 13).reshape(3,4)
print("2D NumPy Array:")
print(array_2d)

2D NumPy Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
# Slice the first two rows and last two columns
sliced_array = array_2d[0:2, 2:4]

print("\nSliced Array (first two rows, last two columns):")
print(sliced_array)


Sliced Array (first two rows, last two columns):
[[3 4]
 [7 8]]


In [45]:
slice_array = array_2d[0:-2, 2:]
print(slice_array)

[[3 4]]
